### ISSUE TITLE
Docker & DataSharing Slides

### ISSUE THREAD

**Issue by miykael** [miykael/workshops#4]
@PeerHerholz - do you already have some updates on the slides for the docker and the data sharing session?

**Comment by PeerHerholz** [comment]
hey @miykael,

jop jop. regarding docker I would say we're using the [docker slides from boston](http://nipy.org/workshops/2017-03-boston/lectures/lesson-container/#1), exchanging parts of the hands on (using the miykael/workshop_marburg docker instead of the nipype/workshop one). 
Furthermore, we should point to the [docker notebook from your tutorial](https://miykael.github.io/nipype_tutorial/notebooks/introduction_docker.html), but definitely should go through the exercises. 

Re: data management & sharing: I uploaded the first parts in [my repo](https://github.com/PeerHerholz/workshops/blob/master/180309_marburg/slides/data_sharing_management.html). The plan would be: intro, data and BIDS, BIDS converters, BIDS apps (MRIQC, mindboggle, FMRIPREP, CPAC --> I would briefly show docker commands, workflow and example outputs) neurodocker, neurovault and openneuro, git, datalad (I guess Michael will be of great help here, hehe), bringing it all together (as you suggested in the program:  the combination of docker, notebooks, data, etc. allows reproducibility, eases up workflows, etc. ). 
This all sounds a lot, but as we're intending to provide a comprehensive overview and the basic skills to apply and use certain tools it should be okay. 

That being said: I was wondering if we should move the nibabel / nilearn sessions to Friday, 4-5 PM, so that we have a nice transition from python to neuroimaging in python. After that I would start the data management & sharing session (5-6:30 PM) and continue with that Saturday morning (9:30 - 10 AM). The other option would be doing the complete data management & sharing session on Friday (4-6 PM) and do nibabel / nilearn Saturday morning. I just thought that talking about "basic" neuroimaging in python before crazy workflow (^^) stuff would be nice.

What do you think?

**Comment by PeerHerholz** [comment]
add on: I would really like to include this [pybids notebook](http://nbviewer.jupyter.org/github/nipy/workshops/blob/master/170327-nipype/notebooks/basic-bids/basic_data_input_bids.ipynb). It's about 10 minutes and very helpful. The question is: within the data management & sharing (somewhere between BIDS converters & apps) or nipype session (inputs, working with bids datasets, etc.)!?

**Comment by miykael** [comment]
hey @PeerHerholz,

I'm ok to adapt the docker slides from boston. Do you want me to work on it to get it in shape?

WOW! I really love your 'data management & sharing' slides. Really cool! And the content seems great. It might sound like a lot, but it's also the backbone of the whole workshop.

Yes, you're right. It's better to make a nice python / neuroimaging transition and also to split up the 1.5h 'data management & sharing session'. I also reduced the time for 'jupyter notebook' to 30min, which should be enough.

**Comment by miykael** [comment]
I remember that I've tried to use the pybids notebook for my nipype example, but somehow struggled at a certain step. I will look into it again and add it to my tutorials :-)

**Comment by PeerHerholz** [comment]
hey @miykael,

Sure, but as it's only about changing the respective docker images (as far as I can tell), I can do it as well. Speaking of which, I was not prepared to do the slides in html...^^. 

Cool, I'm glad that you like it and support the proposed structure! 

Do you want to do the pybids tutorial within the nipype or the data management and sharing session?

**Comment by miykael** [comment]
Hey @PeerHerholz - I already took the liberty to update the docker slides. I've changed some additional points, but nothing big (how to handle windows issues, how to use conda, etc.)

You can of course also use something else than html, I just saw it in the boston workshop and love the simplicity of it. And also, PPT or pdf's are more difficult to change with github.

Hmm.. you're right. Let's do the pybids tutorial with the data management and sharing session.

**Comment by PeerHerholz** [comment]
kk, coolio! 

After some adaption time and being intimidated, I really like it as well.  And, of course, way more open, reproducible and collaborative.

Just to be sure: are you going to do the pybids tutorial notebook or should I?

**Comment by miykael** [comment]
I'm fine if you want to do the pybids tutorial :-) Then I can focus first on the nipype tutorials. I just want to go through them again and make sure that they are good to go.

**Comment by PeerHerholz** [comment]
Okay, as you prefer. I meant the "creation and test process". With "go through / make sure they are good to go", are you referring to the nipype or pybids tutorial?

**Comment by miykael** [comment]
Sorry, I meant the nipype tutorials. I want to take another look at the nipype notebooks and also the notebooks about nilearn, nibabel, etc.

What do you mean with "creation and test process"?

**Comment by PeerHerholz** [comment]
The creation and test process of the pybids tutorial notebook, as we might have to adapt it a bit.

**Comment by miykael** [comment]
Ah, ok good :-)

By the way, I just updated the program of day 1 (https://github.com/miykael/workshops/commit/83c4cad55d68868fbc1917f5e7f88c360e7a31bc). I restructured the "Data exploration with Python" part to have also some content before lunch. If you're ok with the changes, than I will update the schedule on https://openreproneuro2018marburg.github.io/.

**Comment by PeerHerholz** [comment]
Sure thing, looks great!
As discussed before I would say: Friday 4-5 PM, nibabel & nilearn; Friday 5-6:30 PM, data management & sharing I; Saturday 9:30-10 AM, data management & sharing II !?

**Comment by miykael** [comment]
As discussed and already forgotten by me... Your schedule is a good idea, I will move nibabel & nilearn to Friday 4-5 PM. But this would mean that we could move Michael Hanke to 1h earlier (16:00 - 17:30), or I might also be able to use the time for more Nipype examples. What do you think?

**Comment by miykael** [comment]
@PeerHerholz - I think I'm finished with the Nipype day too. I tried to estimate the overall time that I need for each section and it turned out that I have 1h to spare. The program is currently:

```
           09:30 - 10:00 Data management & sharing - Part II
           10:00 - 11:00 -
(~30min)   11:00 - 11:30 Introduction Nipype
(~90min)   11:30 - 13:00 Nipype Interfaces & Workflows
           13:00 - 14:00 Lunch
(~180min)  14:00 - 17:00 Nipype Hands-On: Preprocessing, 1st & 2nd Analysis
```

So, if you want, we could use the time slot from 10-11am for the "data management & sharing" content, perhaps do the pybids part there, too? What do you think? Can you use this part? Otherwise, I can move also everything 1h up ahead and already start with some "Preprocessing Hands-On" before lunch.

**Comment by PeerHerholz** [comment]
Coolio, looks amazing!

In that case, I would extend data management & sharing - part II from 09:30 - 10:30 and start the nipype session accordingly right afterwards at 10:30.
With that we can spend more time on the data management & sharing hands on parts, as well as possibly do some preprocessing before lunch.

**Comment by miykael** [comment]
Perfect! Yes, Friday is probably very dense with the many different topics we want to touch. But Saturday seems to be much more open and fluid and so people could even go back to some topics from Friday if they want to.

**Comment by miykael** [comment]
@PeerHerholz - I sometimes forget about all the content in the nipype tutorial... Couldn't we use the [Datainput for BIDS datasets](https://miykael.github.io/nipype_tutorial/notebooks/basic_data_input_bids.html) notebook as a `pybids` exercise?

**Comment by PeerHerholz** [comment]
@miykael , jop, thought about that as well. However, I would still say that we should introduce it in the data management & sharing session, because there'll be some parts where we can't actually work with data that much as it would simply take too long (e.g. running FMRIPREP or so) and having a pybids hands on would be nice and short practical. What do you think? 
How about we split it, doing the general stuff Friday and the nipype specific stuff Saturday?

**Comment by miykael** [comment]
@PeerHerholz - yes, I agree. It makes more sense to have it in the data management & sharing session. I just meant to say that we perhaps can copy+paste some things from the nipype_tutorial notbeook.

Yes, sounds good to have the general stuff on Friday and nipype specific stuff on Saturday!
